### ISSUE TITLE
Related event of CHO entity does not resolve (Internal Server Error)

### ISSUE THREAD

**Issue by johannesliem** [InTaVia/InTaVia-Backend#165]
The event id linked in the relation of the following cho entity (decoded-id: http://www.wikidata.org/entity/Q4523656), does not resolve (Internal Server Error):

`https://intavia-backend.acdh-dev.oeaw.ac.at/v2/api/entities/aHR0cDovL3d3dy53aWtpZGF0YS5vcmcvZW50aXR5L1E0NTIzNjU2?datasets=http%3A%2F%2Fdata.acdh.oeaw.ac.at%2Fintavia%2Fcho%2Fv5`

Corresponding Event (decoded-id: https://www.intavia.eu/production_event/Q4523656):
`https://intavia-backend.acdh-dev.oeaw.ac.at/v2/api/events/aHR0cHM6Ly93d3cuaW50YXZpYS5ldS9wcm9kdWN0aW9uX2V2ZW50L1E0NTIzNjU2?datasets=http%3A%2F%2Fdata.acdh.oeaw.ac.at%2Fintavia%2Fcho%2Fv5`

**Comment by sennierer** [comment]
thats a specific problem with that object. It was created BC and python actually cant deal with dates BC. Given that we use python internal datetime objects for validating dates this throws an error.
Accoring to [this](https://stackoverflow.com/questions/15857797/bc-dates-in-python) we could switch to astropy package for datetime validation...
Given that this problem is related to a set of objects that are not very interesting for us we will postpone that issue
